local Anims = {
    Idle = {
        Crouch = "http://www.roblox.com/asset/?id=110050689889236",
        Stand = "http://www.roblox.com/asset/?id=180435571",
    },
    Move = {
        Crouch = "http://www.roblox.com/asset/?id=118799512467717",
        Stand = "http://www.roblox.com/asset/?id=180426354",
    },
    UpState = {
        Crouch = "http://www.roblox.com/asset/?id=128359418805559",
    },
    DownState = {
        Crouch = "http://www.roblox.com/asset/?id=132703441448837",
    }
}

return Anims